### ISSUE TITLE
Measurements stuck/don't-change

### ISSUE THREAD

**Issue by frankcohen** [aselectroworks/Arduino-MMC5603NJ#1]
I am using an MMC5603NJ with a custom designed ESP32-S3-Mini device. My repository with board layout and software files is here, https://github.com/frankcohen/ReflectionsOS. Arguino-MMC5603NJ connects with the device using I2C address of 0x5A. I turned on Debug logging and see:

MMC5603NJ(0x5a)]: begin
[MMC5603NJ(0x5a)]: readI2C reg 0x39
[MMC5603NJ(0x5a)]:  <- data[0]:0x00
[MMC5603NJ(0x5a)]: read byte = 0
Product ID: 0x0
[MMC5603NJ(0x5a)]: write byte = 128
[MMC5603NJ(0x5a)]: writeI2C reg 0x1c
[MMC5603NJ(0x5a)]:  -> data[0]:0x80
setContinuousMode
[MMC5603NJ(0x5a)]: write byte = 255
[MMC5603NJ(0x5a)]: writeI2C reg 0x1a
[MMC5603NJ(0x5a)]:  -> data[0]:0xff
[MMC5603NJ(0x5a)]: write byte = 160
[MMC5603NJ(0x5a)]: writeI2C reg 0x1b
[MMC5603NJ(0x5a)]:  -> data[0]:0xa0
[MMC5603NJ(0x5a)]: write byte = 3
[MMC5603NJ(0x5a)]: writeI2C reg 0x1c
[MMC5603NJ(0x5a)]:  -> data[0]:0x03
[MMC5603NJ(0x5a)]: write byte = 16
[MMC5603NJ(0x5a)]: writeI2C reg 0x1d
[MMC5603NJ(0x5a)]:  -> data[0]:0x10
setContinuousMode done
[MMC5603NJ(0x5a)]: readI2C reg 0x00
[MMC5603NJ(0x5a)]:  <- data[0]:0xe0
[MMC5603NJ(0x5a)]:  <- data[1]:0x40
[MMC5603NJ(0x5a)]:  <- data[2]:0x00
[MMC5603NJ(0x5a)]:  <- data[3]:0x01
[MMC5603NJ(0x5a)]:  <- data[4]:0x01
[MMC5603NJ(0x5a)]:  <- data[5]:0x00
[MMC5603NJ(0x5a)]:  <- data[6]:0x00
[MMC5603NJ(0x5a)]:  <- data[7]:0x00
[MMC5603NJ(0x5a)]:  <- data[8]:0x00
Gauss X : +24640.00, Gauss Y : -32767.00, Gauss Z : -32512.00, Gauss : +52324.34
[MMC5603NJ(0x5a)]: readI2C reg 0x00
[MMC5603NJ(0x5a)]:  <- data[0]:0xe0
[MMC5603NJ(0x5a)]:  <- data[1]:0x40
[MMC5603NJ(0x5a)]:  <- data[2]:0x00
[MMC5603NJ(0x5a)]:  <- data[3]:0x01
[MMC5603NJ(0x5a)]:  <- data[4]:0x01
[MMC5603NJ(0x5a)]:  <- data[5]:0x00
[MMC5603NJ(0x5a)]:  <- data[6]:0x00
[MMC5603NJ(0x5a)]:  <- data[7]:0x00
[MMC5603NJ(0x5a)]:  <- data[8]:0x00
Gauss X : +24640.00, Gauss Y : -32767.00, Gauss Z : -32512.00, Gauss : +52324.34

Seems to be getting the same values of ime. What do you recommend I do?

-Frank

**Comment by aselectroworks** [comment]
@frankcohen 
I am sorry that I cannot check my code because I don't have MMC5603NJ PCB now. 
But from your log, you did not read correct Product ID. So something is wrong on I2C bus. 
I think you should aim to be able to read the PID first. You need to check your hardware and software.

**Comment by frankcohen** [comment]
Thanks! I will start with the I2C bus first. The bus is working for another
component. And when I do a bus scan for devices, the other devices appear
and the device I'm having a hard time with does not appear. I'm going to
assume that the chip of the sensor is faulty and try and replace it. Thank
you for your support.

**Comment by aselectroworks** [comment]
Welcome. 
This chip is small WLP package so it is difficult to mount it. 
Hope your project goes well!
